version: '3'

services:
  ai:
    build: ./services/ai
    volumes:
      - ./services/ai:/app
    ports:
      - 8888:8888
    env_file:
      - ./services/ai/.env
    command: jupyter lab --ip 0.0.0.0 --port 8888 --allow-root --ServerApp.token=imt

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
